### ISSUE TITLE
master HEAD enaml-cli cant parse concourse release

### ISSUE THREAD

**Issue by xchapter7x** [enaml-ops/enaml#11] opened 2016-07-14 18:18 UTC
reported from a partner who did a `go get` on the `fdff846a11c3edd908bcf6d1a970fa61bd478416` commit

``````
─➤  LOG_LEVEL=debug ~/go/bin/enaml generate https://bosh.io/d/github.com/concourse/concourse\?v=1.4.1
2016/07/14 14:01:26 D0714 14:01:26.341386 47873 generate.go:36] Adding bind_ip to BaggageclaimJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.341525 47873 generate.go:36] Adding bind_port to BaggageclaimJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.341574 47873 generate.go:36] Adding yeller to BaggageclaimJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.341598 47873 generate.go:36] Adding yeller to BaggageclaimJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.341618 47873 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.341654 47873 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.345109 47873 generate.go:36] Adding blackbox to BlackboxJob with type *Blackbox
2016/07/14 14:01:26 D0714 14:01:26.345146 47873 generate.go:36] Adding blackbox to BlackboxJob with type *Blackbox
2016/07/14 14:01:26 D0714 14:01:26.345165 47873 generate.go:36] Adding blackbox to BlackboxJob with type *Blackbox
2016/07/14 14:01:26 D0714 14:01:26.345184 47873 generate.go:36] Adding syslog to Blackbox with type *Syslog
2016/07/14 14:01:26 D0714 14:01:26.345204 47873 generate.go:36] Adding syslog to Blackbox with type *Syslog
2016/07/14 14:01:26 D0714 14:01:26.345245 47873 generate.go:36] Adding syslog to Blackbox with type *Syslog
2016/07/14 14:01:26 D0714 14:01:26.345284 47873 generate.go:36] Adding destination to Syslog with type *Destination
2016/07/14 14:01:26 D0714 14:01:26.3453 47873 generate.go:36] Adding destination to Syslog with type *Destination
2016/07/14 14:01:26 D0714 14:01:26.345317 47873 generate.go:36] Adding source_dir to Syslog with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.34533 47873 generate.go:36] Adding address to Destination with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.345342 47873 generate.go:36] Adding transport to Destination with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346579 47873 generate.go:36] Adding yeller to TsaJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.34661 47873 generate.go:36] Adding atc to TsaJob with type *Atc
2016/07/14 14:01:26 D0714 14:01:26.346621 47873 generate.go:36] Adding forward_host to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346632 47873 generate.go:36] Adding bind_port to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346646 47873 generate.go:36] Adding host_key to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346662 47873 generate.go:36] Adding host_public_key to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346682 47873 generate.go:36] Adding authorize_generated_worker_key to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346703 47873 generate.go:36] Adding heartbeat_interval to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346722 47873 generate.go:36] Adding authorized_keys to TsaJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346743 47873 generate.go:36] Adding yeller to TsaJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.346762 47873 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346781 47873 generate.go:36] Adding url to Atc with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.346805 47873 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348093 47873 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/14 14:01:26 D0714 14:01:26.348118 47873 generate.go:36] Adding additional_resource_types to GroundcrewJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348132 47873 generate.go:36] Adding yeller to GroundcrewJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.348142 47873 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/14 14:01:26 D0714 14:01:26.348151 47873 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/14 14:01:26 D0714 14:01:26.34816 47873 generate.go:36] Adding baggageclaim to GroundcrewJob with type *Baggageclaim
2016/07/14 14:01:26 D0714 14:01:26.348168 47873 generate.go:36] Adding tags to GroundcrewJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.34818 47873 generate.go:36] Adding https_proxy_url to GroundcrewJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348199 47873 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/14 14:01:26 D0714 14:01:26.348217 47873 generate.go:36] Adding garden to GroundcrewJob with type *Garden
2016/07/14 14:01:26 D0714 14:01:26.348236 47873 generate.go:36] Adding garden to GroundcrewJob with type *Garden
2016/07/14 14:01:26 D0714 14:01:26.348262 47873 generate.go:36] Adding platform to GroundcrewJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348288 47873 generate.go:36] Adding no_proxy to GroundcrewJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.34831 47873 generate.go:36] Adding baggageclaim to GroundcrewJob with type *Baggageclaim
2016/07/14 14:01:26 D0714 14:01:26.348328 47873 generate.go:36] Adding http_proxy_url to GroundcrewJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348349 47873 generate.go:36] Adding yeller to GroundcrewJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.348366 47873 generate.go:36] Adding host to Tsa with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348384 47873 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348403 47873 generate.go:36] Adding port to Tsa with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348419 47873 generate.go:36] Adding private_key to Tsa with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348437 47873 generate.go:36] Adding forward_address to Baggageclaim with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348456 47873 generate.go:36] Adding host_public_key to Tsa with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348475 47873 generate.go:36] Adding address to Garden with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348492 47873 generate.go:36] Adding forward_address to Garden with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348511 47873 generate.go:36] Adding url to Baggageclaim with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.348537 47873 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.351838 47873 generate.go:36] Adding bind_port to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.351877 47873 generate.go:36] Adding publicly_viewable to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.35189 47873 generate.go:36] Adding riemann to AtcJob with type *Riemann
2016/07/14 14:01:26 D0714 14:01:26.3519 47873 generate.go:36] Adding tls_cert to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.35191 47873 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/14 14:01:26 D0714 14:01:26.35192 47873 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/14 14:01:26 D0714 14:01:26.351934 47873 generate.go:36] Adding default_check_interval to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.351951 47873 generate.go:36] Adding tls_key to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.351967 47873 generate.go:36] Adding old_resource_grace_period to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.351987 47873 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/14 14:01:26 D0714 14:01:26.352006 47873 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/14 14:01:26 D0714 14:01:26.352031 47873 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/14 14:01:26 D0714 14:01:26.352048 47873 generate.go:36] Adding tls_bind_port to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352066 47873 generate.go:36] Adding peer_url to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352084 47873 generate.go:36] Adding development_mode to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.35211 47873 generate.go:36] Adding resource_cache_cleanup_interval to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352138 47873 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/14 14:01:26 D0714 14:01:26.352158 47873 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/14 14:01:26 D0714 14:01:26.352185 47873 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/14 14:01:26 D0714 14:01:26.352205 47873 generate.go:36] Adding riemann to AtcJob with type *Riemann
2016/07/14 14:01:26 D0714 14:01:26.352223 47873 generate.go:36] Adding bind_ip to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352237 47873 generate.go:36] Adding external_url to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352252 47873 generate.go:36] Adding basic_auth_username to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352266 47873 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/14 14:01:26 D0714 14:01:26.352277 47873 generate.go:36] Adding postgresql_database to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352286 47873 generate.go:36] Adding yeller to AtcJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.352326 47873 generate.go:36] Adding basic_auth_password to AtcJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352354 47873 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/14 14:01:26 D0714 14:01:26.352376 47873 generate.go:36] Adding yeller to AtcJob with type *Yeller
2016/07/14 14:01:26 D0714 14:01:26.352395 47873 generate.go:36] Adding host to Riemann with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352429 47873 generate.go:36] Adding client_id to GithubAuth with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352449 47873 generate.go:36] Adding client_secret to GithubAuth with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352466 47873 generate.go:36] Adding address to Postgresql with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352479 47873 generate.go:36] Adding role to Postgresql with type *Role
2016/07/14 14:01:26 D0714 14:01:26.352496 47873 generate.go:36] Adding role to Postgresql with type *Role
2016/07/14 14:01:26 D0714 14:01:26.352505 47873 generate.go:36] Adding database to Postgresql with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352514 47873 generate.go:36] Adding auth_url to GithubAuth with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352524 47873 generate.go:36] Adding api_url to GithubAuth with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352537 47873 generate.go:36] Adding port to Riemann with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352547 47873 generate.go:36] Adding token_url to GithubAuth with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.35256 47873 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.35257 47873 generate.go:36] Adding authorize to GithubAuth with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352591 47873 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.352608 47873 generate.go:36] Adding password to Role with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.35262 47873 generate.go:36] Adding name to Role with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.355438 47873 generate.go:36] Adding bind_ip to PostgresqlJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.355472 47873 generate.go:36] Adding bind_port to PostgresqlJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.355489 47873 generate.go:36] Adding databases to PostgresqlJob with type interface{}
2016/07/14 14:01:26 D0714 14:01:26.355498 47873 generate.go:36] Adding max_connections to PostgresqlJob with type interface{}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x989fd]

goroutine 1 [running]:
panic(0x435840, 0xc820012140)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/codegangsta/cli.HandleAction.func1(0xc8200e3550)
    /Users/alex/go/src/github.com/codegangsta/cli/app.go:476 +0x417
panic(0x435840, 0xc820012140)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/enaml-ops/enaml/generators.(*ReleaseJobsGenerator).ProcessFile(0xc8200e2db0, 0xc8200d8dc0, 0x18)
    /Users/alex/go/src/github.com/enaml-ops/enaml/generators/releasejobs.go:45 +0x40d
github.com/enaml-ops/enaml/generators.GenerateReleaseJobsPackage(0x7fff5fbffa72, 0x38, 0x4bd378, 0x6, 0x4c48c0, 0xb, 0x0, 0x0)
    /Users/alex/go/src/github.com/enaml-ops/enaml/generators/releasejobs.go:27 +0x2fc
main.main.func1(0xc820016780, 0x0, 0x0)
    /Users/alex/go/src/github.com/enaml-ops/enaml/cmd/enaml/main.go:65 +0x164
reflect.Value.call(0x3980e0, 0x584d08, 0x13, 0x4bd930, 0x4, 0xc8200e34b0, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x3980e0, 0x584d08, 0x13, 0xc8200e34b0, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/codegangsta/cli.HandleAction(0x3980e0, 0x584d08, 0xc820016780, 0x0, 0x0)
    /Users/alex/go/src/github.com/codegangsta/cli/app.go:485 +0x2ee
github.com/codegangsta/cli.Command.Run(0x4cc900, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x540480, 0x2b, 0x0, ...)
    /Users/alex/go/src/github.com/codegangsta/cli/command.go:186 +0x1301
github.com/codegangsta/cli.(*App).Run(0xc820001200, 0xc82000a150, 0x3, 0x3, 0x0, 0x0)
    /Users/alex/go/src/github.com/codegangsta/cli/app.go:239 +0xa9c
main.main()
    /Users/alex/go/src/github.com/enaml-ops/enaml/cmd/enaml/main.go:103 +0x407```
``````

**Comment by xchapter7x** [comment] 2016-07-14 18:20
fyi above commands work with release https://github.com/enaml-ops/enaml/releases/tag/v0.0.8-de34fd-01ab48

**Comment by prysmakou** [comment] 2016-07-17 18:18
FYI: enaml version v0.0.8-de34fd-01ab48
`LOG_LEVEL=debug ~/go/bin/enaml generate https://bosh.io/d/github.com/concourse/concourse\?v=1.4.1
Could not find release in local cache. Downloading now.
322517272/322517272
completed generating release job structs for  https://bosh.io/d/github.com/concourse/concourse?v=1.4.1
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature`

**Comment by zmb3** [comment] 2016-07-18 16:22
@prysmakou That deprecation warning is nothing to worry about, and was fixed with 3fcc9624b5cab9394c1bbc577e84f239eaf7d7e2.

**Comment by zmb3** [comment] 2016-07-18 16:27
I see how this could happen (we aren't checking for errors other than EOF), but I can't seem to reproduce it.

```
~/s/g/e/enaml ❯❯❯ git rev-parse HEAD
fdff846a11c3edd908bcf6d1a970fa61bd478416
```

```
~/s/g/e/enaml ❯❯❯ go build ./cmd/enaml && LOG_LEVEL=debug ./enaml generate https://bosh.io/d/github.com/concourse/concourse\?v\=1.4.1
2016/07/18 10:06:15 D0718 10:06:15.324387 77554 generate.go:36] Adding bind_ip to BaggageclaimJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.324417 77554 generate.go:36] Adding bind_port to BaggageclaimJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.324427 77554 generate.go:36] Adding yeller to BaggageclaimJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.324435 77554 generate.go:36] Adding yeller to BaggageclaimJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.324442 77554 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.324449 77554 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.325106 77554 generate.go:36] Adding blackbox to BlackboxJob with type *Blackbox
2016/07/18 10:06:15 D0718 10:06:15.325124 77554 generate.go:36] Adding blackbox to BlackboxJob with type *Blackbox
2016/07/18 10:06:15 D0718 10:06:15.325132 77554 generate.go:36] Adding blackbox to BlackboxJob with type *Blackbox
2016/07/18 10:06:15 D0718 10:06:15.325141 77554 generate.go:36] Adding syslog to Blackbox with type *Syslog
2016/07/18 10:06:15 D0718 10:06:15.325155 77554 generate.go:36] Adding syslog to Blackbox with type *Syslog
2016/07/18 10:06:15 D0718 10:06:15.325163 77554 generate.go:36] Adding syslog to Blackbox with type *Syslog
2016/07/18 10:06:15 D0718 10:06:15.325183 77554 generate.go:36] Adding destination to Syslog with type *Destination
2016/07/18 10:06:15 D0718 10:06:15.325197 77554 generate.go:36] Adding destination to Syslog with type *Destination
2016/07/18 10:06:15 D0718 10:06:15.325205 77554 generate.go:36] Adding source_dir to Syslog with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.325214 77554 generate.go:36] Adding address to Destination with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.325222 77554 generate.go:36] Adding transport to Destination with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326238 77554 generate.go:36] Adding host_key to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326256 77554 generate.go:36] Adding host_public_key to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326269 77554 generate.go:36] Adding authorized_keys to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326278 77554 generate.go:36] Adding yeller to TsaJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.326285 77554 generate.go:36] Adding heartbeat_interval to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326292 77554 generate.go:36] Adding bind_port to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.3263 77554 generate.go:36] Adding yeller to TsaJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.326318 77554 generate.go:36] Adding atc to TsaJob with type *Atc
2016/07/18 10:06:15 D0718 10:06:15.326324 77554 generate.go:36] Adding forward_host to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326332 77554 generate.go:36] Adding authorize_generated_worker_key to TsaJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326342 77554 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326354 77554 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.326361 77554 generate.go:36] Adding url to Atc with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327561 77554 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/18 10:06:15 D0718 10:06:15.327592 77554 generate.go:36] Adding baggageclaim to GroundcrewJob with type *Baggageclaim
2016/07/18 10:06:15 D0718 10:06:15.327601 77554 generate.go:36] Adding http_proxy_url to GroundcrewJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327609 77554 generate.go:36] Adding https_proxy_url to GroundcrewJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327617 77554 generate.go:36] Adding no_proxy to GroundcrewJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327625 77554 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/18 10:06:15 D0718 10:06:15.327632 77554 generate.go:36] Adding platform to GroundcrewJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327639 77554 generate.go:36] Adding tags to GroundcrewJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327646 77554 generate.go:36] Adding garden to GroundcrewJob with type *Garden
2016/07/18 10:06:15 D0718 10:06:15.327692 77554 generate.go:36] Adding garden to GroundcrewJob with type *Garden
2016/07/18 10:06:15 D0718 10:06:15.327704 77554 generate.go:36] Adding yeller to GroundcrewJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.327712 77554 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/18 10:06:15 D0718 10:06:15.327719 77554 generate.go:36] Adding tsa to GroundcrewJob with type *Tsa
2016/07/18 10:06:15 D0718 10:06:15.327727 77554 generate.go:36] Adding baggageclaim to GroundcrewJob with type *Baggageclaim
2016/07/18 10:06:15 D0718 10:06:15.327734 77554 generate.go:36] Adding additional_resource_types to GroundcrewJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327742 77554 generate.go:36] Adding yeller to GroundcrewJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.327749 77554 generate.go:36] Adding host to Tsa with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327756 77554 generate.go:36] Adding url to Baggageclaim with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327763 77554 generate.go:36] Adding private_key to Tsa with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327771 77554 generate.go:36] Adding address to Garden with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327778 77554 generate.go:36] Adding forward_address to Garden with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327785 77554 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327792 77554 generate.go:36] Adding port to Tsa with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327803 77554 generate.go:36] Adding host_public_key to Tsa with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327811 77554 generate.go:36] Adding forward_address to Baggageclaim with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.327818 77554 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329552 77554 generate.go:36] Adding tls_cert to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329585 77554 generate.go:36] Adding publicly_viewable to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329595 77554 generate.go:36] Adding development_mode to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329604 77554 generate.go:36] Adding riemann to AtcJob with type *Riemann
2016/07/18 10:06:15 D0718 10:06:15.329611 77554 generate.go:36] Adding riemann to AtcJob with type *Riemann
2016/07/18 10:06:15 D0718 10:06:15.329618 77554 generate.go:36] Adding bind_port to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329626 77554 generate.go:36] Adding basic_auth_username to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329635 77554 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/18 10:06:15 D0718 10:06:15.329642 77554 generate.go:36] Adding resource_cache_cleanup_interval to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329651 77554 generate.go:36] Adding postgresql_database to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.32966 77554 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/18 10:06:15 D0718 10:06:15.329668 77554 generate.go:36] Adding yeller to AtcJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.329675 77554 generate.go:36] Adding peer_url to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329687 77554 generate.go:36] Adding basic_auth_password to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329704 77554 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/18 10:06:15 D0718 10:06:15.329712 77554 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/18 10:06:15 D0718 10:06:15.32972 77554 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/18 10:06:15 D0718 10:06:15.329731 77554 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/18 10:06:15 D0718 10:06:15.329739 77554 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/18 10:06:15 D0718 10:06:15.329746 77554 generate.go:36] Adding tls_key to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329754 77554 generate.go:36] Adding default_check_interval to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329763 77554 generate.go:36] Adding postgresql to AtcJob with type *Postgresql
2016/07/18 10:06:15 D0718 10:06:15.32977 77554 generate.go:36] Adding tls_bind_port to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329778 77554 generate.go:36] Adding external_url to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329786 77554 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/18 10:06:15 D0718 10:06:15.329793 77554 generate.go:36] Adding bind_ip to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329801 77554 generate.go:36] Adding github_auth to AtcJob with type *GithubAuth
2016/07/18 10:06:15 D0718 10:06:15.329808 77554 generate.go:36] Adding old_resource_grace_period to AtcJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329817 77554 generate.go:36] Adding yeller to AtcJob with type *Yeller
2016/07/18 10:06:15 D0718 10:06:15.329824 77554 generate.go:36] Adding host to Riemann with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329831 77554 generate.go:36] Adding port to Riemann with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329842 77554 generate.go:36] Adding token_url to GithubAuth with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329852 77554 generate.go:36] Adding role to Postgresql with type *Role
2016/07/18 10:06:15 D0718 10:06:15.32986 77554 generate.go:36] Adding environment_name to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329868 77554 generate.go:36] Adding client_secret to GithubAuth with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329875 77554 generate.go:36] Adding authorize to GithubAuth with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329884 77554 generate.go:36] Adding role to Postgresql with type *Role
2016/07/18 10:06:15 D0718 10:06:15.329891 77554 generate.go:36] Adding client_id to GithubAuth with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329902 77554 generate.go:36] Adding database to Postgresql with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329909 77554 generate.go:36] Adding address to Postgresql with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329916 77554 generate.go:36] Adding api_url to GithubAuth with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329923 77554 generate.go:36] Adding auth_url to GithubAuth with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329934 77554 generate.go:36] Adding api_key to Yeller with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329943 77554 generate.go:36] Adding password to Role with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.329957 77554 generate.go:36] Adding name to Role with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.331819 77554 generate.go:36] Adding bind_ip to PostgresqlJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.33185 77554 generate.go:36] Adding bind_port to PostgresqlJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.331873 77554 generate.go:36] Adding databases to PostgresqlJob with type interface{}
2016/07/18 10:06:15 D0718 10:06:15.331889 77554 generate.go:36] Adding max_connections to PostgresqlJob with type interface{}
completed generating release job structs for  https://bosh.io/d/github.com/concourse/concourse?v=1.4.1
```

It looks like the program was built against `codegangsta/cli` in the user's `GOPATH` and not from the `vendor` directory:

_/Users/alex/go/src/github.com/codegangsta/cli/app.go:476_

I suspect `go get` pulled the latest version but the user never ran a `glide install` to pull the correct vendored dependencies.  This step is missing from the README - I'll fix that.

**Comment by zmb3** [comment] 2016-07-22 14:17
Added error checks in 9a04c1d972618adb8a121a45900b4659f1a20493 and updated the README in 36c31c303f2c14fc8aaae656dc97c64e92cdd651.

**Closed as completed by zmb3** 2016-07-22 14:17 UTC
